In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv("jobs_data.csv")

In [7]:
df.head()

,job_id,job_role,company,experience,salary,location,rating,reviews,key_skills,posted_on,job_link,company_link
0,181224917811,GN - Strategy - MC - SC&O - SC Digital Core Ar...,Accenture,3-6 Yrs,Not disclosed,"Hyderabad, Chennai, Bengaluru",3.9,52479 Reviews,"sap ariba,presentation skills,solution impleme...",1 Day Ago,https://www.naukri.com/job-listings-gn-strateg...,https://www.naukri.com/accenture-jobs-careers-...
1,181224906322,GN - SC&O - BPM - Senior Manager,Accenture,2-4 Yrs,Not disclosed,"Gurugram, Bengaluru, Delhi / NCR",3.9,52479 Reviews,"spend analysis,market research,sales and opera...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-bp...,https://www.naukri.com/accenture-jobs-careers-...
2,181224906320,GN - SC&O - S&P - CLM - Associate Manager,Accenture,1-5 Yrs,Not disclosed,"Gurugram, Bengaluru, Delhi / NCR",3.9,52479 Reviews,"Sourcing,PowerBI,procurement,digital sourcing,...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-s-...,https://www.naukri.com/accenture-jobs-careers-...
3,181224904080,GN - SONG - Service - Command Center of Future...,Accenture,12-15 Yrs,Not disclosed,"New Delhi, Gurugram, Bengaluru",3.9,52479 Reviews,"cloud solutions,WFM solutions,AI,Customer Enga...",1 Day Ago,https://www.naukri.com/job-listings-gn-song-se...,https://www.naukri.com/accenture-jobs-careers-...
4,181224904079,GN - SC&O - S&P - CLM - Manager,Accenture,8-13 Yrs,Not disclosed,"New Delhi, Gurugram, Bengaluru",3.9,52479 Reviews,"Procurement,Sourcing,Supply Chain Management,p...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-s-...,https://www.naukri.com/accenture-jobs-careers-...

In [9]:
df.rename(columns={'key_skills': 'skills'}, inplace=True)

## 1. Data Description

In [16]:
df.shape

(61773, 12)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61773 entries, 0 to 61772
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   job_id        61773 non-null  int64
 1   job_role      61773 non-null  object
 2   company       41025 non-null  object
 3   experience    60154 non-null  object
 4   salary        61773 non-null  object
 5   location      60663 non-null  object
 6   rating        41029 non-null  float64
 7   reviews       41029 non-null  object
 8   skills        61279 non-null  object
 9   posted_on     61773 non-null  object
 10  job_link      61773 non-null  object
 11  company_link  41027 non-null  object
dtypes: float64(1), int64(1), object(10)
memory usage: 5.7+ MB

In [20]:
df.describe()

             job_id        rating
count  6.177300e+04  41029.000000
mean   1.467205e+11      3.807102
std    4.238888e+10      0.513798
min    1.012400e+10      1.000000
25%    1.212240e+11      3.600000
50%    1.412240e+11      3.900000
75%    1.812240e+11      4.000000
max    3.110240e+11      5.000000

## 2. Handling Null Value

In [23]:
df.isnull().sum()

job_id              0
job_role            0
company         20748
experience       1619
salary              0
location         1110
rating          20744
reviews         20744
skills            494
posted_on           0
job_link            0
company_link    20746
dtype: int64

In [27]:
df.dropna()

,job_id,job_role,company,experience,salary,location,rating,reviews,skills,posted_on,job_link,company_link
0,181224917811,GN - Strategy - MC - SC&O - SC Digital Core Ar...,Accenture,3-6 Yrs,Not disclosed,"Hyderabad, Chennai, Bengaluru",3.9,52479 Reviews,"sap ariba,presentation skills,solution impleme...",1 Day Ago,https://www.naukri.com/job-listings-gn-strateg...,https://www.naukri.com/accenture-jobs-careers-...
1,181224906322,GN - SC&O - BPM - Senior Manager,Accenture,2-4 Yrs,Not disclosed,"Gurugram, Bengaluru, Delhi / NCR",3.9,52479 Reviews,"spend analysis,market research,sales and opera...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-bp...,https://www.naukri.com/accenture-jobs-careers-...
2,181224906320,GN - SC&O - S&P - CLM - Associate Manager,Accenture,1-5 Yrs,Not disclosed,"Gurugram, Bengaluru, Delhi / NCR",3.9,52479 Reviews,"Sourcing,PowerBI,procurement,digital sourcing,...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-s-...,https://www.naukri.com/accenture-jobs-careers-...
3,181224904080,GN - SONG - Service - Command Center of Future...,Accenture,12-15 Yrs,Not disclosed,"New Delhi, Gurugram, Bengaluru",3.9,52479 Reviews,"cloud solutions,WFM solutions,AI,Customer Enga...",1 Day Ago,https://www.naukri.com/job-listings-gn-song-se...,https://www.naukri.com/accenture-jobs-careers-...
4,181224904079,GN - SC&O - S&P - CLM - Manager,Accenture,8-13 Yrs,Not disclosed,"New Delhi, Gurugram, Bengaluru",3.9,52479 Reviews,"Procurement,Sourcing,Supply Chain Management,p...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-s-...,https://www.naukri.com/accenture-jobs-careers-...
...,...,...,...,...,...,...,...,...,...,...,...,...
61758,111224500987,Territory Business Executive,Sandoz,1-4 Yrs,Not disclosed,"Kota, Jaipur, Bikaner, Jodhpur",4.0,382 Reviews,"Sales planning,Networking,Cardiovascular,Confl...",8 Days Ago,https://www.naukri.com/job-listings-territory-...,https://www.naukri.com/sandoz-jobs-careers-203162
61759,111224500984,Purchase Manager,Royaldrive,2-7 Yrs,Not disclosed,"Kochi, Thrissur, Kozhikode, Thiruvananthapuram",4.8,3 Reviews,"Automobile,Purchase Management,UPS,RDMS,Manage...",8 Days Ago,https://www.naukri.com/job-listings-purchase-m...,https://www.naukri.com/royaldrive-jobs-careers...
61760,111224500983,Asst Manager - Sales,Royaldrive,2-4 Yrs,Not disclosed,"Malappuram, Kozhikode, Thiruvananthapuram",4.8,3 Reviews,"Sales,Stock management,Consulting,Management,A...",8 Days Ago,https://www.naukri.com/job-listings-asst-manag...,https://www.naukri.com/royaldrive-jobs-careers...
61761,111224500982,Sales Consultant,Royaldrive,2-7 Yrs,Not disclosed,"Kochi, Malappuram, Kozhikode, Thiruvananthapuram",4.8,3 Reviews,"Sales,Consulting,Management,Sales consulting",8 Days Ago,https://www.naukri.com/job-listings-sales-cons...,https://www.naukri.com/royaldrive-jobs-careers...
61762,111224500968,Front End Developer,Computer Frontline Consultancy Services (CFCS),3-8 Yrs,Not disclosed,Noida,3.5,9 Reviews,"IT services,Backend,Front end,GIT,html5,Javasc...",8 Days Ago,https://www.naukri.com/job-listings-front-end-...,https://www.naukri.com/computer-frontline-cons...

#### ---->If we drop all the data which has a null value in any of the column we left with only 65% data of raw data

### Replacing the Null values with "missing"

In [29]:
df.fillna("missing",inplace=True)

C:\Users\Sweety\AppData\Local\Temp\ipykernel_17772\1256532227.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'missing' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("missing",inplace=True)

In [33]:
df.sample(10)

,job_id,job_role,company,experience,salary,location,rating,reviews,skills,posted_on,job_link,company_link
45921,131224004443,Salesforce Application Testing,missing,4-7 Yrs,6-12 Lacs PA,Hybrid - Bengaluru,missing,missing,"Selenium Automation,Salesforce Application Tes...",7 Days Ago,https://www.naukri.com/job-listings-salesforce...,missing
26929,121224501434,Production Assistant,missing,1-3 Yrs,Not disclosed,Mumbai,missing,missing,"Printing,Administration,Visual Effects,Linux,D...",7 Days Ago,https://www.naukri.com/job-listings-production...,missing
55078,121224503982,Design Engineer (Plant 3D),Veolia,6-10 Yrs,Not disclosed,Bengaluru,4.2,184 Reviews,"3D,3D modeling,Stress analysis,Piping stress a...",7 Days Ago,https://www.naukri.com/job-listings-design-eng...,https://www.naukri.com/veolia-jobs-careers-267125
32015,111224917636,Project Manager-JAVA\nDevelopment Manager,missing,9-14 Yrs,Not disclosed,Navi Mumbai,missing,missing,"Development Management,J2Ee Development,Java D...",8 Days Ago,https://www.naukri.com/job-listings-project-ma...,missing
61272,111224916538,Business Analyst in Data Analytics,missing,3-8 Yrs,5.5-15 Lacs PA,Chennai,missing,missing,"Business Analyst,Data Analyst,Stakeholder Mana...",8 Days Ago,https://www.naukri.com/job-listings-business-a...,missing
52950,61224904000,Associate Data Architect,missing,3-7 Yrs,Not disclosed,"Maharashtra, Maharashtra",missing,missing,"metadata,data management,data architecture,dat...",8 Days Ago,https://www.naukri.com/job-listings-associate-...,missing
22201,240524010466,Executive Assistant,Polymed,2-6 Yrs,Not disclosed,Ballabhgarh,3.7,539 Reviews,"Communication Skills,Travel Booking,Calendar M...",1 Day Ago,https://www.naukri.com/job-listings-executive-...,https://www.naukri.com/polymed-jobs-careers-88239
59580,121224506138,Drupal Developer,Ebizon Net Info,3-8 Yrs,Not disclosed,Noida,3.3,70 Reviews,"Drupal,Content management,Configuration manage...",7 Days Ago,https://www.naukri.com/job-listings-drupal-dev...,https://www.naukri.com/ebizon-net-info-jobs-ca...
28651,121224003727,"Total Station Surveyor - Chennai,bangalore,vel...",Dbc Construction,3-8 Yrs,2-4 Lacs PA,"Chennai, Bengaluru, Vellore",2.9,24 Reviews,"Survey,surveyor,Total Station,Auto Level,Level...",8 Days Ago,https://www.naukri.com/job-listings-total-stat...,https://www.naukri.com/dbc-construction-jobs-c...
45084,161224501049,Lead Engineer Application Security,missing,6-8 Yrs,Not disclosed,"Hubli, Mangaluru, Mysuru, Bengaluru, Belgaum",missing,missing,"Linux,Testing tools,Coding,Information securit...",3 Days Ago,https://www.naukri.com/job-listings-lead-engin...,missing

## 3. Handling Duplicate Values

In [36]:
df.duplicated().sum()

1185

In [38]:
df=df.drop_duplicates()

In [40]:
df.duplicated().sum()

0

In [42]:
df.shape

(60588, 12)

## 4. Saving the cleaned data

In [45]:
df.to_csv('jobs_data_preprocessed.csv', index = False)

In [47]:
df.to_excel("jobs_data_preprocessed.xlsx", index=False)